name: Verify New Releases

on:
  workflow_dispatch:

jobs:
  create_issue:
    name: Create new release issue
    runs-on: ubuntu-latest
    env:
      SYNAPSE_CURRENT_VERSION: 1.101.1
    permissions:
      issues: write
    steps:
      - id: synapse
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: element-hq
          repo: synapse
          excludes: prerelease, draft

      - name: Create new release issue
        if: ${{ env.SYNAPSE_CURRENT_VERSION != steps.synapse.outputs.release }}
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Synapse new release is available
          LABELS: new-release
          BODY: |
            ### Synapse new release is available.

            - Current: ${{ env.SYNAPSE_CURRENT_VERSION }}
            - Latest: ${{ steps.synapse.outputs.release }}
          PINNED: true
          CLOSE_PREVIOUS: true
